x-node-base-image: &node-base-image node:23-bookworm

volumes:
  uv:

services:
  slack:
    image: *node-base-image
    command: npx -y supergateway --port 8002 --stdio "npx -y @modelcontextprotocol/server-slack"
    ports:
      - 8002:8002
    env_file:
      - ./servers/slack/.env
  memory:
    image: *node-base-image
    entrypoint: /root/servers/memory/docker-entrypoint.sh
    command: npx -y supergateway --port 8004 --stdio "node /root/miror_servers/src/memory/dist/index.js"
    ports:
      - 8004:8004
    environment:
      - MEMORY_FILE_PATH=/root/servers/memory/memory.json
    volumes:
      - ./servers/memory/:/root/servers/memory/
      - ./miror_servers/:/root/miror_servers/
    working_dir: /root
  sequential-thinking:
    image: *node-base-image
    command: npx -y supergateway --port 8005 --stdio "npx -y @modelcontextprotocol/server-sequential-thinking"
    ports:
      - 8005:8005
